micronaut:
  application:
    name: mnJdbcJoin
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/item
    driverClassName: org.postgresql.Driver
    username: item
    password: ''
logger:
  levels:
    io.micronaut.data.query: TRACE
